{"links":{"static":"docs/api/pal/function/AggregateError","html":"docs/api/pal/function/AggregateError/index.html","fragment":"docs/api/pal/function/AggregateError/index-fragment.html","self":"docs/api/pal/function/AggregateError/index.json"},"name":"AggregateError","kindString":"Function","flags":{"isExported":true},"signatures":[{"name":"AggregateError","kindString":"Call signature","flags":{},"comment":{"shortText":"Creates an instance of Error that aggregates and preserves an innerError.","returns":"The Error instance.\n"},"parameters":[{"name":"message","kindString":"Parameter","flags":{},"comment":{"text":"The error message."},"type":{"type":"instrinct","name":"string"}},{"name":"innerError","kindString":"Parameter","flags":{"isOptional":true},"comment":{"text":"The inner error message to aggregate."},"type":{"type":"reference","name":"Error"}},{"name":"skipIfAlreadyAggregate","kindString":"Parameter","flags":{"isOptional":true},"comment":{"text":"Indicates to not wrap the inner error if it itself already has an innerError."},"type":{"type":"instrinct","name":"boolean"}}],"type":{"type":"reference","name":"Error"}}],"sources":[{"fileName":"aurelia-pal.d.ts","line":334,"character":38}]}