{"links":{"static":"docs/api/fetch-client/interface/Interceptor/property/responseError","html":"docs/api/fetch-client/interface/Interceptor/property/responseError/index.html","fragment":"docs/api/fetch-client/interface/Interceptor/property/responseError/index-fragment.html","self":"docs/api/fetch-client/interface/Interceptor/property/responseError/index.json"},"name":"responseError","kindString":"Property","flags":{"isExported":true,"isOptional":true},"comment":{"shortText":"Handles fetch errors and errors generated by previous interceptors. This\nfunction acts as a Promise rejection handler. It may rethrow the error\nto propagate the failure, or return a new Response to recover.","tags":[{"tag":"param","text":"The rejection value from the fetch request or from a\nprevious interceptor.","param":"error"},{"tag":"returns","text":"The response; or a Promise for one.\n"}]},"sources":[{"fileName":"aurelia-fetch-client.d.ts","line":47,"character":15}],"type":{"type":"reflection","declaration":{"id":971,"name":"__type","kind":65536,"kindString":"Type literal","flags":{},"signatures":[{"id":972,"name":"__call","kind":4096,"kindString":"Call signature","flags":{},"parameters":[{"id":973,"name":"error","kind":32768,"kindString":"Parameter","flags":{},"type":{"type":"intrinsic","name":"any"}},{"id":974,"name":"request","kind":32768,"kindString":"Parameter","flags":{"isOptional":true},"type":{"type":"reference","name":"Request"}}],"type":{"type":"union","types":[{"type":"reference","name":"Response"},{"type":"reference","name":"Promise","typeArguments":[{"type":"reference","name":"Response"}]}]}}],"sources":[{"fileName":"aurelia-fetch-client.d.ts","line":47,"character":17}]}}}